<?php
/**
 * Created by PhpStorm.
 * User: SECONDRED
 * Date: 24.12.2017
 * Time: 18:50
 */

namespace anu\elements\db;

use Anu;
use anu\records\UserRecord;

class UserQuery extends ElementQuery{
    public $username;
    public $email;

    public $id;

    /**
     * Custom search
     *
     * @param $value
     * @return $this
     */
    public function username($value){
        $this->username = $value;

        return $this;
    }

    /**
     * Custom search
     *
     * @param $value
     * @return $this
     */
    public function email($value)
    {
        $this->email = $value;

        return $this;
    }

    /**
     * Custom search
     *
     * @param $value
     * @return $this
     */
    public function id($value){
        $this->id = $value;

        return $this;
    }

    /**
     * @return bool
     */
    protected function beforePrepare(): bool{
        // join in the products table

        $this->joinElementTable('users');

        $record = new UserRecord();
        $attributes = $record->getAttributes();
        $values = array();
        foreach ($attributes as $k => $v){
            $values[] = 'users.'.$k;
        }

        // select the price column
        $this->query->select($values);

        if($this->username){
            $this->subQuery->andWhere(['users.username' => $this->username]);
        }

        if($this->email){
            $this->subQuery->andWhere(['users.username' => $this->email]);
        }

        if($this->id){
            $this->subQuery->andWhere(['users.id' => $this->id]);
        }

        return parent::beforePrepare();
    }


    public function init(){

        parent::init(); // TODO: Change the autogenerated stub
    }
}